// This file is generated by HostedSnapshotRegistryGenerator.

import HostedSnapshotHelper
import LocalExamplePackage
import SnapshotTesting
import SwiftUI
import Testing

@Suite
struct LocalExamplePackageHostedSnapshotTests {
    @Test
    @MainActor
    func test_HostedViewSnapshotTests_testAlertViewSheetOpenState() {
        withHostedSnapshotContext(
          snapshotDirectory: "/Users/tmelle/projects/HostedSnapshotHelper/Example/LocalExamplePackage/Tests/LocalExamplePackageTests/__Snapshots__/HostedViewSnapshotTests",
          testName: "testAlertViewSheetOpenState"
        ) {
          let sut = AlertView(isAlertPresented: true, toggleOn: true)

                assertHostedSnapshot(of: sut, devices: [("iPhone13", .iPhone13)], wait: 1.0)
        }
    }

    @Test
    @MainActor
    func test_HostedViewSnapshotTests_testSheetViewSheetOpenState() {
        withHostedSnapshotContext(
          snapshotDirectory: "/Users/tmelle/projects/HostedSnapshotHelper/Example/LocalExamplePackage/Tests/LocalExamplePackageTests/__Snapshots__/HostedViewSnapshotTests",
          testName: "testSheetViewSheetOpenState"
        ) {
          let sut = SheetView(isSheetPresented: true, toggleOn: false)

                assertHostedSnapshot(of: sut, devices: [("iPhone13", .iPhone13)], wait: 1.0)
        }
    }
}